<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.gyyun.ds</groupId>
        <artifactId>gyyun</artifactId>
        <version>3.4.3-SNAPSHOT</version>
    </parent>
    <artifactId>gyyun-datasource-plugin</artifactId>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>

    <modules>
        <module>gyyun-datasource-sqlserver</module>
        <module>gyyun-datasource-clickhouse</module>
        <module>gyyun-datasource-db2</module>
        <module>gyyun-datasource-hive</module>
        <module>gyyun-datasource-mysql</module>
        <module>gyyun-datasource-oceanbase</module>
        <module>gyyun-datasource-oracle</module>
        <module>gyyun-datasource-postgresql</module>
        <module>gyyun-datasource-spark</module>
        <module>gyyun-datasource-presto</module>
        <module>gyyun-datasource-api</module>
        <module>gyyun-datasource-all</module>
        <module>gyyun-datasource-kyuubi</module>
        <module>gyyun-datasource-trino</module>
        <module>gyyun-datasource-starrocks</module>
        <module>gyyun-datasource-azure-sql</module>
        <module>gyyun-datasource-dameng</module>
        <module>gyyun-datasource-ssh</module>
        <module>gyyun-datasource-zeppelin</module>
        <module>gyyun-datasource-databend</module>
        <module>gyyun-datasource-snowflake</module>
        <module>gyyun-datasource-vertica</module>
        <module>gyyun-datasource-doris</module>
        <module>gyyun-datasource-k8s</module>
        <module>gyyun-datasource-hana</module>
        <module>gyyun-datasource-aliyunserverlessspark</module>
        <module>gyyun-datasource-dolphindb</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.gyyun.ds</groupId>
                <artifactId>gyyun-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
